school/classroom/urls.py
from django.urls import path
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('thank_you/', views.ThankYou.as_view(), name='thank_you'), 
    path('teacher_form/', views.TeacherFormView.as_view(), name='teacher_form'),
    path('contact/', views.ContactFormView.as_view(), name='contact_form'),
    path('teacher_list/', views.TeacherListView.as_view(), name='teacher_list'),
    path('teacher_detail/<int:pk>', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('teacher_update/<int:pk>', views.TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher_confirm_delete/<int:pk>', views.TeacherDeleteView.as_view(), name='delete_teacher')
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.first_name} {self.last_name} teaches {self.subject}.'

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=30)
    message = forms.CharField(max_length=100, widget=forms.Textarea)

school/classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import ContactForm
from .models import Teacher

# Create your views here.
class HomePage(TemplateView):
    template_name = 'classroom/home.html'

class ThankYou(TemplateView):
    template_name = 'classroom/thank_you.html'

class TeacherFormView(CreateView):
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('classroom:thank_you')

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    success_url = reverse_lazy('classroom:thank_you')

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)
    
class TeacherListView(ListView):
    model = Teacher
    context_object_name = 'teacher_list'

class TeacherDetailView(DetailView):
    model = Teacher

class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('classroom:teacher_list')

class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('classroom:teacher_list')

school/classroom/templates/classroom/contact.html
<h1>Contact.HTML</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

school/classroom/templates/classroom/home.html
<h1>Home Page</h1>
<ul>
    <li>
        <a href="{% url 'classroom:thank_you' %}">Click Here Thank You Page</a>
    </li>
</ul>
<ul>
    <li>
        <a href="{% url 'classroom:teacher_form' %}">Click Here Teacher Form Page</a>
    </li>
</ul>
<ul>
    <li>
        <a href="{% url 'classroom:contact_form' %}">Click Here Contact Form Page</a>
    </li>
</ul>
<ul>
    <li>
        <a href="{% url 'classroom:teacher_list' %}">Click Here Teacher List Page</a>
    </li>
</ul>

school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete?</h1>
<h2>{{teacher}}</h2>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

school/classroom/templates/classroom/teacher_detail.html
<h1>Teacher Detail View</h1>
{{teacher}}

school/classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

school/classroom/templates/classroom/teacher_list.html
<h1>Teacher List</h1>
<ul>
    {% for name in teacher_list %}
    <li>
        <a href="/classroom/teacher_detail/{{name.id}}">{{name.first_name}} {{name.last_name}}</a>
        <ul>
            <li>
                <a href="/classroom/teacher_update/{{name.id}}">Update</a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="/classroom/teacher_confirm_delete/{{name.id}}">Delete</a>
            </li>
        </ul>
    </li>
    {% endfor %}
</ul>

school/classroom/templates/classroom/thank_you.html
<h1>Thank You</h1>